
package com.tuankiet.brandname.ws.core;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "sms", targetNamespace = "http://core.ws.brandname.tuankiet.com", wsdlLocation = "http://bc.vht.com.vn:8440/vht/services/sms?wsdl")
public class Sms
    extends Service
{

    private final static URL SMS_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://bc.vht.com.vn:8440/vht/services/sms?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        SMS_WSDL_LOCATION = url;
    }

    public Sms(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Sms() {
        super(SMS_WSDL_LOCATION, new QName("http://core.ws.brandname.tuankiet.com", "sms"));
    }

    /**
     * 
     * @return
     *     returns SmsPortType
     */
    @WebEndpoint(name = "smsHttpSoap11Endpoint")
    public SmsPortType getSmsHttpSoap11Endpoint() {
        return (SmsPortType)super.getPort(new QName("http://core.ws.brandname.tuankiet.com", "smsHttpSoap11Endpoint"), SmsPortType.class);
    }

}
