
package com.tuankiet.brandname.ws.core;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "smsPortType", targetNamespace = "http://core.ws.brandname.tuankiet.com")
public interface SmsPortType {


    /**
     * 
     * @param phone
     * @param account
     * @param from
     * @param code
     * @param sms
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "urn:sendSms")
    @WebResult(targetNamespace = "http://core.ws.brandname.tuankiet.com")
    @RequestWrapper(localName = "sendSms", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.SendSms")
    @ResponseWrapper(localName = "sendSmsResponse", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.SendSmsResponse")
    public Integer sendSms(
        @WebParam(name = "code", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String code,
        @WebParam(name = "account", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String account,
        @WebParam(name = "phone", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String phone,
        @WebParam(name = "from", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String from,
        @WebParam(name = "sms", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String sms);

    /**
     * 
     * @param sender
     * @param account
     * @param code
     * @param sms
     * @param phones
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "urn:sendSmsToListPhone")
    @WebResult(targetNamespace = "http://core.ws.brandname.tuankiet.com")
    @RequestWrapper(localName = "sendSmsToListPhone", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.SendSmsToListPhone")
    @ResponseWrapper(localName = "sendSmsToListPhoneResponse", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.SendSmsToListPhoneResponse")
    public Integer sendSmsToListPhone(
        @WebParam(name = "code", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String code,
        @WebParam(name = "account", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String account,
        @WebParam(name = "phones", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String phones,
        @WebParam(name = "sender", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String sender,
        @WebParam(name = "sms", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String sms);

    /**
     * 
     * @param username
     * @param partnerId
     * @param code
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getStatusPartner")
    @WebResult(targetNamespace = "http://core.ws.brandname.tuankiet.com")
    @RequestWrapper(localName = "getStatusPartner", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.GetStatusPartner")
    @ResponseWrapper(localName = "getStatusPartnerResponse", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.GetStatusPartnerResponse")
    public String getStatusPartner(
        @WebParam(name = "username", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String username,
        @WebParam(name = "code", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String code,
        @WebParam(name = "partnerId", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String partnerId);

    /**
     * 
     * @param phone
     * @param account
     * @param from
     * @param code
     * @param sms
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "urn:sendUni")
    @WebResult(targetNamespace = "http://core.ws.brandname.tuankiet.com")
    @RequestWrapper(localName = "sendUni", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.SendUni")
    @ResponseWrapper(localName = "sendUniResponse", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.SendUniResponse")
    public Integer sendUni(
        @WebParam(name = "code", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String code,
        @WebParam(name = "account", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String account,
        @WebParam(name = "phone", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String phone,
        @WebParam(name = "from", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String from,
        @WebParam(name = "sms", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String sms);

    /**
     * 
     * @param account
     * @param code
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getBrandNames")
    @WebResult(targetNamespace = "http://core.ws.brandname.tuankiet.com")
    @RequestWrapper(localName = "getBrandNames", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.GetBrandNames")
    @ResponseWrapper(localName = "getBrandNamesResponse", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.GetBrandNamesResponse")
    public String getBrandNames(
        @WebParam(name = "account", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String account,
        @WebParam(name = "code", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String code);

    /**
     * 
     * @param account
     * @param code
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "urn:getBalance")
    @WebResult(targetNamespace = "http://core.ws.brandname.tuankiet.com")
    @RequestWrapper(localName = "getBalance", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.GetBalance")
    @ResponseWrapper(localName = "getBalanceResponse", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.GetBalanceResponse")
    public Integer getBalance(
        @WebParam(name = "account", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String account,
        @WebParam(name = "code", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String code);

    /**
     * 
     * @param sign
     * @param phone
     * @param deliveryTime
     * @param account
     * @param from
     * @param code
     * @param sms
     * @param ipAddress
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "urn:sendFlash")
    @WebResult(targetNamespace = "http://core.ws.brandname.tuankiet.com")
    @RequestWrapper(localName = "sendFlash", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.SendFlash")
    @ResponseWrapper(localName = "sendFlashResponse", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.SendFlashResponse")
    public Integer sendFlash(
        @WebParam(name = "code", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String code,
        @WebParam(name = "account", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String account,
        @WebParam(name = "phone", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String phone,
        @WebParam(name = "from", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String from,
        @WebParam(name = "sms", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String sms,
        @WebParam(name = "ipAddress", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String ipAddress,
        @WebParam(name = "deliveryTime", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String deliveryTime,
        @WebParam(name = "sign", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String sign);

    /**
     * 
     * @param phone
     * @param account
     * @param from
     * @param code
     * @param sms
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "urn:sendSmsWap")
    @WebResult(targetNamespace = "http://core.ws.brandname.tuankiet.com")
    @RequestWrapper(localName = "sendSmsWap", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.SendSmsWap")
    @ResponseWrapper(localName = "sendSmsWapResponse", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.SendSmsWapResponse")
    public Integer sendSmsWap(
        @WebParam(name = "code", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String code,
        @WebParam(name = "account", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String account,
        @WebParam(name = "phone", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String phone,
        @WebParam(name = "from", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String from,
        @WebParam(name = "sms", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String sms);

    /**
     * 
     * @param sender
     * @param account
     * @param code
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "urn:createSender")
    @WebResult(targetNamespace = "http://core.ws.brandname.tuankiet.com")
    @RequestWrapper(localName = "createSender", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.CreateSender")
    @ResponseWrapper(localName = "createSenderResponse", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.CreateSenderResponse")
    public Integer createSender(
        @WebParam(name = "account", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String account,
        @WebParam(name = "code", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String code,
        @WebParam(name = "sender", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String sender);

    /**
     * 
     * @param phone
     * @param account
     * @param from
     * @param code
     * @param sms
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "urn:sendSmsFlash")
    @WebResult(targetNamespace = "http://core.ws.brandname.tuankiet.com")
    @RequestWrapper(localName = "sendSmsFlash", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.SendSmsFlash")
    @ResponseWrapper(localName = "sendSmsFlashResponse", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.SendSmsFlashResponse")
    public Integer sendSmsFlash(
        @WebParam(name = "code", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String code,
        @WebParam(name = "account", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String account,
        @WebParam(name = "phone", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String phone,
        @WebParam(name = "from", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String from,
        @WebParam(name = "sms", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String sms);

    /**
     * 
     * @param sign
     * @param phone
     * @param deliveryTime
     * @param account
     * @param from
     * @param code
     * @param sms
     * @param ipAddress
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "urn:send")
    @WebResult(targetNamespace = "http://core.ws.brandname.tuankiet.com")
    @RequestWrapper(localName = "send", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.Send")
    @ResponseWrapper(localName = "sendResponse", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.SendResponse")
    public Integer send(
        @WebParam(name = "code", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String code,
        @WebParam(name = "account", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String account,
        @WebParam(name = "phone", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String phone,
        @WebParam(name = "from", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String from,
        @WebParam(name = "sms", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String sms,
        @WebParam(name = "ipAddress", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String ipAddress,
        @WebParam(name = "deliveryTime", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String deliveryTime,
        @WebParam(name = "sign", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String sign);

    /**
     * 
     * @param phone
     * @param partnerId
     * @param account
     * @param from
     * @param code
     * @param sms
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "urn:sendSmsReport")
    @WebResult(targetNamespace = "http://core.ws.brandname.tuankiet.com")
    @RequestWrapper(localName = "sendSmsReport", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.SendSmsReport")
    @ResponseWrapper(localName = "sendSmsReportResponse", targetNamespace = "http://core.ws.brandname.tuankiet.com", className = "com.tuankiet.brandname.ws.core.SendSmsReportResponse")
    public Integer sendSmsReport(
        @WebParam(name = "code", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String code,
        @WebParam(name = "account", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String account,
        @WebParam(name = "phone", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String phone,
        @WebParam(name = "from", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String from,
        @WebParam(name = "sms", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String sms,
        @WebParam(name = "partnerId", targetNamespace = "http://core.ws.brandname.tuankiet.com")
        String partnerId);

}
